# Generated by Django 3.0.7 on 2020-06-23 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiviyPeriods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('real_name', models.CharField(max_length=50)),
                ('tz', models.CharField(max_length=20)),
                ('activity_periods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.ActiviyPeriods')),
            ],
        ),
        migrations.DeleteModel(
            name='Hero',
        ),
    ]
